# Spotify authentication
SPOTIPY_CLIENT_ID = None # CHANGE ME
SPOTIPY_CLIENT_SECRET = None # CHANGE ME
SPOTIPY_SCOPE = "user-read-playback-state"
SPOTIPY_REDERICT_URI = "http://127.0.0.1:5001"
SPOTIPY_PLAYBACK_UPDATE_INTERVAL = 10

N_LEDS = 287
SERIAL_PORT = "/dev/ttyUSB0"
BAUD_RATE = 2000000
