from .animation1 import Animation1
from .animation2 import Animation2
from .animation3 import Animation3
from .animation4 import Animation4
from .bar import Bar
from .fill import Fill
from .sinus import Sinus
from .slide import Slide
from .wave2d import Wave2D
